import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className=''>
        <h1 className='text-slate-800 font-bold'>Tuantq</h1>
      </main>
    </>
  )
}
